### ISSUE TITLE
How can i get feature image PHOG Filter on Android ?

### ISSUE THREAD

**Issue by ddthanhdat** [mmayo888/ImageFilter#1]
Hello admin,

I want to use model in android. But i can get feature PHOG Filter on Android. How can i do it?

Thanks

**Comment by mmayo888** [comment]
This project is a filter for WEKA. If you want to use one of the filters on Android, you would first need to find out how to install and run WEKA on Android. It should then be straightforward to install the filter and then use it from WEKA. I would suggest asking on the WEKA mailing list about WEKA/Android, or doing a google search.
