### ISSUE TITLE
Using in jdk6

### ISSUE THREAD

**Issue by MJ-DEV91** [mmayo888/ImageFilter#3]
Hi. I want to use this filter in a production environment and unfortunately the jdk version on this server is 6. and then when I want to compile my code, I'll face with an error:
```
Error:(35, 33) java:  cannot access weka.filters.SimpleBatchFilter
bad class file: weka\filters\SimpleBatchFilter.class(weka\filters:SimpleBatchFilter.class)
class file has wrong version 52.0, should be 50.0
Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by mmayo888** [comment]
Hi, the image filters were developed using Java 7/8, so there are no guarantees it will work on Java 6. You could try recompiling the filter from the source code and hope it works. However, several libraries are used by the filter and I am not sure if these would be compatible or not. You would have to do some testing.

Mike
